### ISSUE TITLE
Rewards received from testnet are included in mainnet estimated reward calculation

### ISSUE THREAD

**Issue by adamphivo** [adamphivo/brubeckscan#22]
Currently, rewards distributed during Testnet are taken into account when calculating rewards to be received for Mainnet. 

This cause the app to display a wrong amount of rewards for some users.

Example : 

1) 
- User A has received 50 DATA during Testnet
- User A has received 25 DATA during Mainnet
- The app is going to calculate that User A has already received 75 DATA during mainnet when he only received 25 DATA.

2) 
- User B has received 100 DATA during Testnet
- User B has mined 50 DATA this month ( Mainnet ) and has not received his/her rewards yet.
- The app is going to calculate that rewards to be received for User B is -50 ( where it should be 50)

Current request to the Graph API : https://github.com/adamphivo/brubeckscan/blob/main/src/routes/api/nodes/_getDataSent.ts

Solution : 

- Filter out rewards sent during testnet of the graph API response.

Benefits : 

- Correct & precise estimation of rewards

**Comment by fonty1** [comment]
This might help, 

```
{
  erc20Transfers(where: {
    from: "${streamrAddress}",
    to: "${address}",
    timestamp_gt: 1640995200 # Jan 1st 2022
  }) {
    value
    timestamp
  }
}
```
