### ISSUE TITLE
"Invalid time value" Error

### ISSUE THREAD

**Issue by Kryptol0g** [adamphivo/brubeckscan#26]
https://ibb.co/WGKCcWF
https://ibb.co/G24RMGQ
https://ibb.co/xFFCdNV
https://ibb.co/RySpM6k

**Comment by adamphivo** [comment]
Hi,
Thank you for opening the issue and for the screenshots. 
I am going to work on this issue quickly.

**Comment by adamphivo** [comment]
Fixed with : https://github.com/adamphivo/brubeckscan/releases/tag/1.1.5
